FROM ubuntu:22.04

EXPOSE 6363
ARG DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:named-data/ppa
RUN apt update
RUN apt install -y nfd


ADD addNode.sh .
# Custom conf file, which enabled 'localhop_security' and disables 'auto_prefix_propagate'
ADD nfd.conf /usr/local/etc/ndn

CMD ["nfd"]
